[package]
name = "tokio-smoltcp"
version = "0.1.0"
authors = ["spacemeowx2 <spacemeowx2@gmail.com>"]
edition = "2018"
description = "Tokio smoltcp"
license = "MIT OR Apache-2.0"

[dependencies]
futures = "0.3"
pin-project-lite = "0.2.6"
tokio = { version = "1.6.1", features = ["time", "rt"] }
tokio-util = "0.6.7"

[dependencies.smoltcp]
version = "0.7.0"
default-features = false
features = [ "std", "async", "socket-tcp", "ethernet" ]
# "medium-ethernet", "medium-ip"
# remove git when 0.8.0 released
# git = "https://github.com/smoltcp-rs/smoltcp.git"
# rev = "7e62f6883b287e9a9dc4054c83c64811c3ace6b1"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
pcap = "0.8.1"
structopt = "0.3"

[features]
default = [ "proto-ipv4", "proto-ipv6", "raw_socket" ]
proto-ipv4 = [ "smoltcp/proto-ipv4" ]
proto-ipv6 = [ "smoltcp/proto-ipv6" ]
raw_socket = [ "smoltcp/socket-raw" ]

[[example]]
name = "pcap"
